language: python
services:
  - docker
python:
  - "3.6"
install:
  - make deps
script:
  - make lint
  - make test
  - make docker_build
  - make test_xunit
after_success:
  - make docker_push
deploy:
  provider: heroku
  app: mighty-journey-43896
  api_key: ${HEROKU_API_KEY}
